input-utils: update to 1.1
- change upstream URL
- update to 1.1 release
- delete obsolete patches (they are in upstream)

patch 001
- fix compile on sys with sh->dash (Debian,Ubuntu)
Error:
Make.config:1: *** empty variable name.  Stop.
Reason: echo -e in mk/Autoconf.mk

patch 002:
- use path of Linux headers from environment (INPUT)
for generating files with name.sh
Error depending on Kernel:
In file included from input.c:48:0:
KEY.h:243:4: error: 'KEY_WWAN' undeclared here (not in a function)
  [ KEY_WWAN         ] = "WWAN",

fixes https://dev.openwrt.org/ticket/14028

unsure if the right header is included
compile tested

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>
Signed-off-by: Florian Fainelli <florian@openwrt.org>

git-svn-id: svn://svn.openwrt.org/openwrt/packages@40725 3c298f89-4303-0410-b956-a3cf2f4a3e73